//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlasticMetal.MobileSuit {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlasticMetal.MobileSuit.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 All OK 的本地化字符串。
        /// </summary>
        internal static string AllOK {
            get {
                return ResourceManager.GetString("AllOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 . All rights reserved. 的本地化字符串。
        /// </summary>
        internal static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown Error 的本地化字符串。
        /// </summary>
        internal static string ApplicationError {
            get {
                return ResourceManager.GetString("ApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  length not match 的本地化字符串。
        /// </summary>
        internal static string AutoDynamicParameter_Parse__0__length_not_match {
            get {
                return ResourceManager.GetString("AutoDynamicParameter_Parse__0__length_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  not in dictionary 的本地化字符串。
        /// </summary>
        internal static string AutoDynamicParameter_Parse__0__not_in_dictionary___1__ {
            get {
                return ResourceManager.GetString("AutoDynamicParameter_Parse__0__not_in_dictionary___1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  not match format 的本地化字符串。
        /// </summary>
        internal static string AutoDynamicParameter_Parse__0__not_match_format______ {
            get {
                return ResourceManager.GetString("AutoDynamicParameter_Parse__0__not_match_format______", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Built-In Commands: 的本地化字符串。
        /// </summary>
        internal static string Bic {
            get {
                return ResourceManager.GetString("Bic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All of the Built-In Commands Can be used as default with the starting&apos; 的本地化字符串。
        /// </summary>
        internal static string BicExp1 {
            get {
                return ResourceManager.GetString("BicExp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos; as prefix. 的本地化字符串。
        /// </summary>
        internal static string BicExp2 {
            get {
                return ResourceManager.GetString("BicExp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string CommandParsingFailure {
            get {
                return ResourceManager.GetString("CommandParsingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copyright (c)  的本地化字符串。
        /// </summary>
        internal static string CopyrightC {
            get {
                return ResourceManager.GetString("CopyrightC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Completed 的本地化字符串。
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keyboard Interrupt 的本地化字符串。
        /// </summary>
        internal static string Interrupt {
            get {
                return ResourceManager.GetString("Interrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Command 的本地化字符串。
        /// </summary>
        internal static string InvalidCommand {
            get {
                return ResourceManager.GetString("InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Log has no Cache! Make it Cached! 的本地化字符串。
        /// </summary>
        internal static string LogNotCached {
            get {
                return ResourceManager.GetString("LogNotCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type &apos; 的本地化字符串。
        /// </summary>
        internal static string LsHelp1 {
            get {
                return ResourceManager.GetString("LsHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos; to get all available command. 的本地化字符串。
        /// </summary>
        internal static string LsHelp2 {
            get {
                return ResourceManager.GetString("LsHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command Not Found 的本地化字符串。
        /// </summary>
        internal static string MemberNotFound {
            get {
                return ResourceManager.GetString("MemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commands: 的本地化字符串。
        /// </summary>
        internal static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos; to get MobileSuit Build in commands. 的本地化字符串。
        /// </summary>
        internal static string MsHelp2 {
            get {
                return ResourceManager.GetString("MsHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string OnError {
            get {
                return ResourceManager.GetString("OnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Powered By  的本地化字符串。
        /// </summary>
        internal static string PoweredBy {
            get {
                return ResourceManager.GetString("PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t find available DI route for given providers. 的本地化字符串。
        /// </summary>
        internal static string PromptGeneratorBuilder_NoRoute {
            get {
                return ResourceManager.GetString("PromptGeneratorBuilder_NoRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return Value 的本地化字符串。
        /// </summary>
        internal static string ReturnValue {
            get {
                return ResourceManager.GetString("ReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Running 的本地化字符串。
        /// </summary>
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tasks:  的本地化字符串。
        /// </summary>
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To View Built-In Commands, use Command &apos; 的本地化字符串。
        /// </summary>
        internal static string ViewBic {
            get {
                return ResourceManager.GetString("ViewBic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Work Instance: 的本地化字符串。
        /// </summary>
        internal static string WorkInstance {
            get {
                return ResourceManager.GetString("WorkInstance", resourceCulture);
            }
        }
    }
}
