//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HitRefresh.MobileSuit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HitRefresh.MobileSuit.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All OK.
        /// </summary>
        internal static string AllOK {
            get {
                return ResourceManager.GetString("AllOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . All rights reserved..
        /// </summary>
        internal static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        internal static string ApplicationError {
            get {
                return ResourceManager.GetString("ApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  length not match.
        /// </summary>
        internal static string AutoDynamicParameter_Parse__0__length_not_match {
            get {
                return ResourceManager.GetString("AutoDynamicParameter_Parse__0__length_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  not in dictionary.
        /// </summary>
        internal static string AutoDynamicParameter_Parse__0__not_in_dictionary___1__ {
            get {
                return ResourceManager.GetString("AutoDynamicParameter_Parse__0__not_in_dictionary___1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  not match format.
        /// </summary>
        internal static string AutoDynamicParameter_Parse__0__not_match_format______ {
            get {
                return ResourceManager.GetString("AutoDynamicParameter_Parse__0__not_match_format______", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-In Commands:.
        /// </summary>
        internal static string Bic {
            get {
                return ResourceManager.GetString("Bic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All of the Built-In Commands Can be used as default with the starting&apos;.
        /// </summary>
        internal static string BicExp1 {
            get {
                return ResourceManager.GetString("BicExp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; as prefix..
        /// </summary>
        internal static string BicExp2 {
            get {
                return ResourceManager.GetString("BicExp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CommandParsingFailure {
            get {
                return ResourceManager.GetString("CommandParsingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) .
        /// </summary>
        internal static string CopyrightC {
            get {
                return ResourceManager.GetString("CopyrightC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Interrupt.
        /// </summary>
        internal static string Interrupt {
            get {
                return ResourceManager.GetString("Interrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Command.
        /// </summary>
        internal static string InvalidCommand {
            get {
                return ResourceManager.GetString("InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Log has no Cache! Make it Cached!.
        /// </summary>
        internal static string LogNotCached {
            get {
                return ResourceManager.GetString("LogNotCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;.
        /// </summary>
        internal static string LsHelp1 {
            get {
                return ResourceManager.GetString("LsHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; to get all available command..
        /// </summary>
        internal static string LsHelp2 {
            get {
                return ResourceManager.GetString("LsHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Not Found.
        /// </summary>
        internal static string MemberNotFound {
            get {
                return ResourceManager.GetString("MemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands:.
        /// </summary>
        internal static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; to get MobileSuit Build in commands..
        /// </summary>
        internal static string MsHelp2 {
            get {
                return ResourceManager.GetString("MsHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string OnError {
            get {
                return ResourceManager.GetString("OnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Powered By .
        /// </summary>
        internal static string PoweredBy {
            get {
                return ResourceManager.GetString("PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find available DI route for given providers..
        /// </summary>
        internal static string PromptGeneratorBuilder_NoRoute {
            get {
                return ResourceManager.GetString("PromptGeneratorBuilder_NoRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Value.
        /// </summary>
        internal static string ReturnValue {
            get {
                return ResourceManager.GetString("ReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks: .
        /// </summary>
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To View Built-In Commands, use Command &apos;.
        /// </summary>
        internal static string ViewBic {
            get {
                return ResourceManager.GetString("ViewBic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Instance:.
        /// </summary>
        internal static string WorkInstance {
            get {
                return ResourceManager.GetString("WorkInstance", resourceCulture);
            }
        }
    }
}
